data:
  min_salary: 1000
  lower_percentile: 2
  upper_percentile: 98
  salary_scale: 0.001
  test_size: 0.2
  random_state: 42
features:
  cardinality:
    max_categories: 50
    min_frequency: 100
    other_category: Other
    drop_other_from:
    - Country
    - DevType
    - Industry
    - Age
    - ICorPM
    - OrgSize
    - Employment
  encoding:
    drop_first: true
model:
  n_estimators: 5000
  learning_rate: 0.056803456466335424
  max_depth: 4
  min_child_weight: 16
  random_state: 42
  n_jobs: -1
  early_stopping_rounds: 50
  subsample: 0.9378495066287903
  colsample_bytree: 0.589604213410477
  reg_alpha: 1.2493619591455039
  reg_lambda: 0.006641605590505938
  gamma: 1.269496538435438
training:
  verbose: false
  save_model: true
  model_path: models/model.pkl
guardrails:
  max_mape_per_category: 100
  max_abs_pct_diff: 100
