data:
  min_salary: 1000
  lower_percentile: 2
  upper_percentile: 98
  salary_scale: 0.001
  test_size: 0.2
  random_state: 42
features:
  cardinality:
    max_categories: 20
    min_frequency: 50
    other_category: Other
    drop_other_from:
    - Country
    - DevType
    - Industry
    - Age
    - ICorPM
  encoding:
    drop_first: true
model:
  n_estimators: 5000
  learning_rate: 0.05963413021247507
  max_depth: 3
  min_child_weight: 20
  random_state: 42
  n_jobs: -1
  early_stopping_rounds: 50
  subsample: 0.9259971339904378
  colsample_bytree: 0.8104418840320677
  reg_alpha: 0.00020079319919233748
  reg_lambda: 0.035007213429529116
  gamma: 3.3605247926570816
training:
  verbose: false
  save_model: true
  model_path: models/model.pkl
guardrails:
  min_r2_per_category: 0.2
  max_abs_pct_diff: 20
