Country:
- Australia
- Austria
- Belgium
- Brazil
- Canada
- Czech Republic
- Denmark
- Finland
- France
- Germany
- Greece
- Hungary
- India
- Israel
- Italy
- Mexico
- Netherlands
- New Zealand
- Norway
- Poland
- Portugal
- Romania
- South Africa
- Spain
- Sweden
- Switzerland
- Turkey
- Ukraine
- United Kingdom of Great Britain and Northern Ireland
- United States of America
EdLevel:
- Associate degree (A.A., A.S., etc.)
- Bachelor's degree (B.A., B.S., B.Eng., etc.)
- Master's degree (M.A., M.S., M.Eng., MBA, etc.)
- Other
- Primary/elementary school
- Professional degree (JD, MD, Ph.D, Ed.D, etc.)
- Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)
- Some college/university study without earning a degree
DevType:
- AI/ML engineer
- Academic researcher
- Applied scientist
- Architect, software or solutions
- Cloud infrastructure engineer
- Cybersecurity or InfoSec professional
- Data engineer
- Data or business analyst
- Data scientist
- Database administrator or engineer
- DevOps engineer or professional
- Developer, AI apps or physical AI
- Developer, QA or test
- Developer, back-end
- Developer, desktop or enterprise applications
- Developer, embedded applications or devices
- Developer, front-end
- Developer, full-stack
- Developer, game or graphics
- Developer, mobile
- Engineering manager
- Founder, technology or otherwise
- Product manager
- Project manager
- Retired
- Senior executive (C-suite, VP, etc.)
- Student
- Support engineer or analyst
- System administrator
Industry:
- Banking/Financial Services
- Computer Systems Design and Services
- Energy
- Fintech
- Government
- Healthcare
- Higher Education
- Insurance
- Internet, Telecomm or Information Services
- Manufacturing
- Media & Advertising Services
- Retail and Consumer Services
- Software Development
- Transportation, or Supply Chain
Age:
- 18-24 years old
- 25-34 years old
- 35-44 years old
- 45-54 years old
- 55-64 years old
- 65 years or older
ICorPM:
- Individual contributor
- People manager
OrgSize:
- 1,000 to 4,999 employees
- 10,000 or more employees
- 100 to 499 employees
- 20 to 99 employees
- 5,000 to 9,999 employees
- 500 to 999 employees
- I don't know
- Just me - I am a freelancer, sole proprietor, etc.
- Less than 20 employees
